### ISSUE TITLE
Accelrometer and Gyro self-test

### ISSUE THREAD

**Issue by rohithr2597** [kriswiner/ICM42688#5]
For the accelerometer self-test, it's mentioned that it should be between 50 and 1200 mg and for gyro, the DPS should be greater than 60. But from the datasheet, it's unclear how you calculated this minimum and maximum range. Can you please explain this?

**Comment by kriswiner** [comment]
If you look into the bowels of Invensense's poxy C code library for this
sensor you will find this in the self test driver file:

/* Formula to get ST_OTP based on FS and ST_code */
#if defined(ICM42686)
#define INV_ST_OTP_EQUATION(FS, ST_code)
(uint32_t)((1310/pow(2,3-FS))*pow(1.01, ST_code-1)+0.5)
#else
#define INV_ST_OTP_EQUATION(FS, ST_code)
(uint32_t)((2620/pow(2,3-FS))*pow(1.01, ST_code-1)+0.5)
#endif

/* Pass/Fail criteria */
#define MIN_RATIO_GYRO         0.5f /* expected ratio greater than 0.5 */
#define MIN_ST_GYRO_DPS        60   /* expected values greater than 60dps */
#define MAX_ST_GYRO_OFFSET_DPS 20   /* expected offset less than 20 dps */

#define MIN_RATIO_GYRO  0.5f /* expected ratio greater than 0.5 */
#define MAX_RATIO_GYRO  1.5f /* expected ratio lower than 1.5 */
#define MIN_ST_ACCEL_MG 50   /* expected values in [50mgee;1200mgee] */
#define MAX_ST_ACCEL_MG 1200
