### ISSUE TITLE
Add an open source license, such as MIT and/or Apache 2.0

### ISSUE THREAD

**Issue by TheButlah** [kriswiner/ICM42688#7]
I'd like to reference this code in some other work, but without an open source license, I won't be able to look at it.

Could you add a MIT and/or Apache 2.0 license?

**Comment by kriswiner** [comment]
The license for the code is as follows:

"Library may be used freely and without limit with proper attribution."

Anything you might add would be more restrictive, but you are free to do so
as long as the attribution command is followed.

**Comment by TheButlah** [comment]
Personally, I'd feel more comfortable if it had a commonly recognized license instead of an ad-hoc/custom but permissive one. But thanks for the clarification at least :)

**Comment by kriswiner** [comment]
You may add one, as long as you respect the original (broader albeit
ad-hoc) license.
